algoritmo "temperatura"
// Função :
// Autor :
// Data : 03/11/2021
// Seção de Declarações 
var
    C, F:Real
    K: Inteiro
inicio
      Escreval("Informe a temperatura em fahrenheit:")
      Leia(F)
      C <- (F-32)/1.8
      Escreval("A temperatura em Celsios e de" , c)
      
      Escreval("Informe a temperatura em kelvin:")
      Leia(K)
      C <- K-273
      Escreval("A temperatura em Celsios e de" , c)
// Seção de Comandos 
fimalgoritmo
